/// The Dart half of the cross-language surface contract.
///
/// ## Why this exists
///
/// BAROGROOVE describes its UI in Python and renders it in Dart, and until this
/// test neither side ever looked at the other. A Python change could rename a
/// property, or describe an array as a `ChildTemplate` over a prototype this
/// catalog has no builder for, and the payload would still parse, still
/// validate, still pass the entire Python suite — and then land in front of a
/// user as
///
///     Missing data: "genreCorridor": no corridors bound to "items"
///
/// Three separate regressions shipped exactly that way. The renderer degrades
/// gracefully by design, which is right for a user and useless for CI: nothing
/// failed, so nothing was caught. A screenshot from the user was the test.
///
/// So `scripts/gen_a2ui_fixtures.py` runs the *real* surface builders and
/// writes `test/fixtures/a2ui_surfaces.json`; this test drives the *real*
/// renderer over it. `tests/test_a2ui_surface_contract.py` keeps the fixture
/// byte-identical to what Python emits today.
///
/// ## The two shapes, and why both are covered
///
///   `flutter` — the messages after the REST adapter in `routes/surfaces.py`.
///               This is what `GET /api/surfaces/*` serves and what the app
///               renders, so it gets a full widget render and must produce no
///               placeholder at all.
///   `raw`     — what `backend/app/a2ui/surfaces.py` emits, which is what the
///               MCP stream serves. It legitimately uses generic A2UI
///               vocabulary this catalog has no builders for (`Stack`, and the
///               template prototypes `ThemeChip` / `GenreOption` / `TrackRow` /
///               `AlmanacEntry` / `SkyDialSpoke`), so a full render is the
///               wrong assertion. What is asserted instead is the thing that
///               actually broke: every self-drawing feature component resolves
///               its array through the real binding code.
///
/// The REST adapter used to inject those array bindings on its way to Flutter.
/// That is precisely why the app looked fine while the MCP stream and the
/// published catalog.json stayed broken — so covering only the adapted shape
/// would rebuild the original blind spot.
///
/// ## How it fails
///
/// Drop `items` from the ThemeChips node in `surfaces.py` and you get, in
/// order:
///
///   1. `tests/test_a2ui_surface_contract.py` — the checked-in fixture is
///      stale. Regenerate it.
///   2. this test, naming the offender:
///
///        themes/raw: ThemeChips "themeChips" resolves none of
///        [items, themes] to a non-empty list
///
///      and, for the adapted shape:
///
///        themes/flutter degraded 1 component(s):
///          - Missing data — "themeChips": no themes bound to "items"
library;

import 'dart:convert';
import 'dart:io';

import 'package:barogroove/a2ui/catalog.dart';
import 'package:barogroove/a2ui/data_model.dart';
import 'package:barogroove/a2ui/messages.dart';
import 'package:barogroove/a2ui/renderer.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

/// Generated by `.venv/bin/python -m scripts.gen_a2ui_fixtures`.
const String _fixturePath = 'test/fixtures/a2ui_surfaces.json';

/// Component type -> the property names its widget will accept the array
/// under, in the order the widget tries them.
///
/// This mirrors `SELF_DRAWING_BINDINGS` in `tests/test_a2ui_surface_contract.py`
/// on purpose: the two languages must agree on the vocabulary, and the only way
/// to notice that they have stopped agreeing is to write it down twice and let
/// one of the two suites go red.
const Map<String, List<String>> _selfDrawing = <String, List<String>>{
  'ThemeChips': <String>['items', 'themes'],
  'GenreCorridor': <String>['items', 'corridors'],
  'TrackList': <String>['tracks', 'items'],
  'AlmanacTimeline': <String>['entries', 'items'],
  'TelemetryInspector': <String>['entries', 'trajectories', 'items'],
};

/// Big enough that nothing is culled for being off-screen — a component that
/// never builds cannot be observed degrading.
const Size _viewport = Size(1600, 8000);

/// Every self-drawing type the binding group actually reached, accumulated
/// across surfaces so a type that stops being emitted anywhere is noticed.
final Set<String> _exercised = <String>{};

const List<String> _surfaces = <String>[
  'sky',
  'themes',
  'playlist',
  'rationale',
  'almanac',
  'telemetry',
];

void main() {
  late Map<String, dynamic> fixtures;

  setUpAll(() {
    final File file = File(_fixturePath);
    expect(
      file.existsSync(),
      isTrue,
      reason: '$_fixturePath is missing. Regenerate it from the repo root:\n'
          '  .venv/bin/python -m scripts.gen_a2ui_fixtures',
    );
    fixtures = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  });

  tearDown(() => A2uiPlaceholder.debugOnDegrade = null);

  // ==========================================================================
  test('the fixture covers every surface the backend publishes', () {
    // A surface that quietly stops being generated is a surface that quietly
    // stops being contract-tested.
    expect(
      fixtures.keys.toList()..sort(),
      <String>[
        'almanac',
        'error',
        'playlist',
        'rationale',
        'sky',
        'telemetry',
        'themes',
      ],
    );
    for (final MapEntry<String, dynamic> entry in fixtures.entries) {
      expect(
        (entry.value as Map<String, dynamic>).keys.toList()..sort(),
        <String>['flutter', 'raw'],
        reason: 'surface "${entry.key}" must publish both shapes',
      );
    }
  });

  // ==========================================================================
  group('the published shape renders with no missing data', () {
    for (final String surface in _surfaces) {
      testWidgets(surface, (WidgetTester tester) async {
        final List<String> degradations = <String>[];
        A2uiPlaceholder.debugOnDegrade = (A2uiPlaceholder p) {
          final String line = '${p.title} — ${p.detail}';
          if (!degradations.contains(line)) degradations.add(line);
        };

        tester.view.physicalSize = _viewport;
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.reset);

        final List<A2uiMessage> messages =
            A2uiMessage.parseBatch(_envelopes(fixtures, surface, 'flutter'));
        final A2uiSurfaceController controller = A2uiSurfaceController(
          surfaceId: surface,
          catalog: buildBarogrooveCatalog(),
        )..applyAll(messages);

        expect(
          controller.issues.map((SurfaceIssue i) => i.summary).toList(),
          isEmpty,
          reason: '$surface/flutter produced message-level issues',
        );
        expect(controller.hasRoot, isTrue,
            reason: '$surface/flutter has no component with id "root"');

        await tester.pumpWidget(
          ProviderScope(
            child: MaterialApp(
              home: Scaffold(
                body: SingleChildScrollView(
                  child: A2uiSurfaceView(controller: controller),
                ),
              ),
            ),
          ),
        );
        await tester.pumpAndSettle();

        expect(
          degradations,
          isEmpty,
          reason: '$surface/flutter degraded ${degradations.length} '
              'component(s):\n'
              '${degradations.map((String d) => '  - $d').join('\n')}\n\n'
              'Each line is a component the renderer could not bind against '
              'the payload the backend actually serves. Fix it at the layer '
              'that owns it: a missing or misnamed property is a surface- '
              'builder bug, an unknown component type is a catalog bug. Do '
              'not "fix" it by teaching the widget one more spelling.',
        );
      });
    }
  });

  // ==========================================================================
  group('every self-drawing component resolves its array on both shapes', () {
    for (final String surface in _surfaces) {
      for (final String shape in <String>['raw', 'flutter']) {
        test('$surface/$shape', () {
          final List<String> failures = <String>[];
          final Set<String> seenTypes = <String>{};
          var checked = 0;

          final SurfaceDataModel model = SurfaceDataModel();
          final List<A2uiComponent> components = <A2uiComponent>[];

          for (final A2uiMessage message
              in A2uiMessage.parseBatch(_envelopes(fixtures, surface, shape))) {
            if (message is CreateSurface) {
              components.addAll(message.components);
              final JsonMap? initial = message.initialDataModel;
              if (initial != null) model.apply('/', initial);
            } else if (message is UpdateComponents) {
              components.addAll(message.components);
            } else if (message is UpdateDataModel) {
              model.apply(message.path, message.contents);
            }
          }

          for (final A2uiComponent component in components) {
            final List<String>? accepted = _selfDrawing[component.type];
            if (accepted == null) continue;
            checked++;
            seenTypes.add(component.type);

            final bool bound = accepted.any((String key) {
              final DynamicValue? d = component.dyn(key);
              if (d == null || d.kind != DynamicKind.path) return false;
              final Object? value = model.resolve(d.pointer!);
              return value is List && value.isNotEmpty;
            });

            if (!bound) {
              failures.add(
                '${component.type} "${component.id}" resolves none of '
                '$accepted to a non-empty list '
                '(properties: ${component.properties.keys.toList()..sort()})',
              );
            }
          }

          expect(
            failures,
            isEmpty,
            reason: '$surface/$shape:\n'
                '${failures.map((String f) => '  - $f').join('\n')}\n\n'
                'These components draw their own list, so a ChildTemplate over '
                'a prototype this catalog has no builder for resolves to '
                'nothing and the component degrades to a grey placeholder. The '
                'array must arrive as a JSON Pointer from the surface builder, '
                'so that the MCP stream and the REST route both get it.',
          );
          _exercised.addAll(seenTypes);
          // `checked` is allowed to be zero here: `sky` and `rationale` carry
          // no list-drawing component at all. That every type IS covered
          // somewhere is asserted once, below.
          expect(checked, greaterThanOrEqualTo(0));
        });
      }
    }
  });

  // ==========================================================================
  test('every self-drawing type is exercised by at least one surface', () {
    // Declared after the group above so it runs once they have all reported.
    // A component that quietly stops being emitted stops being tested, and
    // that is exactly how a binding regression gets back in.
    expect(
      _exercised,
      equals(_selfDrawing.keys.toSet()),
      reason: 'never reached by any fixture surface: '
          '${_selfDrawing.keys.toSet().difference(_exercised)}',
    );
  });

  // ==========================================================================
  testWidgets('the themes surface really draws all eight themes and corridors',
      (WidgetTester tester) async {
    // Belt and braces for the surface that regressed three times. No
    // placeholder is necessary but not sufficient: an empty array draws no
    // placeholder in some components either, it just draws nothing at all.
    tester.view.physicalSize = _viewport;
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    final A2uiSurfaceController controller = A2uiSurfaceController(
      surfaceId: 'themes',
      catalog: buildBarogrooveCatalog(),
    )..applyAll(
        A2uiMessage.parseBatch(_envelopes(fixtures, 'themes', 'flutter')));

    await tester.pumpWidget(
      ProviderScope(
        child: MaterialApp(
          home: Scaffold(
            body: SingleChildScrollView(
              child: A2uiSurfaceView(controller: controller),
            ),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    for (final String name in <String>[
      'Petrichor',
      'Golden Hour',
      'Nordic Fog',
      'Storm Front',
      'Heatwave Cruise',
      'Blue Hour',
      'First Frost',
      'Sirocco',
    ]) {
      expect(find.text(name), findsOneWidget, reason: 'theme "$name"');
    }
    expect(find.text('Krautrock'), findsOneWidget);
    expect(find.text('Ambient'), findsOneWidget);
  });
}

List<Object?> _envelopes(
  Map<String, dynamic> fixtures,
  String surface,
  String shape,
) =>
    ((fixtures[surface] as Map<String, dynamic>)[shape] as List<dynamic>)
        .cast<Object?>();
